/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import backendcontrollers.CustomerController;
import functions.CheckingSingleQuote;
import functions.DocCodeGenarate;
import functions.Validator;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import model.Customer;

/**
 *
 * @author Sameera
 */
public class FormNewCustomer extends javax.swing.JDialog {

    /**
     * Creates new form FormNewCustomer
     */
    boolean atBillingTime;
    public FormNewCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }
    
     public FormNewCustomer(java.awt.Frame parent, boolean modal,boolean atBillingTime) {
        super(parent, modal);
        initComponents();
        this.atBillingTime = atBillingTime;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        txtCustomerName = new javax.swing.JTextField();
        lbl_description = new javax.swing.JLabel();
        lbl_accountType = new javax.swing.JLabel();
        txtAddressline1 = new javax.swing.JTextField();
        txtAddressline2 = new javax.swing.JTextField();
        lbl_accountType2 = new javax.swing.JLabel();
        lbl_accountType3 = new javax.swing.JLabel();
        lbl_accountType4 = new javax.swing.JLabel();
        lbl_accountType5 = new javax.swing.JLabel();
        txtTele1 = new javax.swing.JTextField();
        txtTele2 = new javax.swing.JTextField();
        txtMobile1 = new javax.swing.JTextField();
        txtMobile2 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbl_accountType6 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        Fax = new javax.swing.JLabel();
        txtContactperson = new javax.swing.JTextField();
        lbl_description1 = new javax.swing.JLabel();
        txtCreditLimit = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Customer");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 51, 153));
        btnCancel.setText("Cancel");
        btnCancel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE,0),"Esc");

        btnCancel.getActionMap().put("Esc", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                btnCancel.doClick();
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(0, 51, 153));
        btnNew.setText("Save");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        lbl_description.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_description.setForeground(new java.awt.Color(102, 102, 102));
        lbl_description.setText("Credit limit (Rs)");

        lbl_accountType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_accountType.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType.setText("Contact person");

        txtAddressline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressline1ActionPerformed(evt);
            }
        });

        txtAddressline2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressline2ActionPerformed(evt);
            }
        });

        lbl_accountType2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_accountType2.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType2.setText("Address line 1");

        lbl_accountType3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_accountType3.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType3.setText("Address line 2");

        lbl_accountType4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_accountType4.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType4.setText("Telephone");

        lbl_accountType5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_accountType5.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType5.setText("Mobile num.");

        txtTele1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTele1ActionPerformed(evt);
            }
        });
        txtTele1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTele1KeyTyped(evt);
            }
        });

        txtTele2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTele2ActionPerformed(evt);
            }
        });
        txtTele2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTele2KeyTyped(evt);
            }
        });

        txtMobile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobile1ActionPerformed(evt);
            }
        });
        txtMobile1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobile1KeyTyped(evt);
            }
        });

        txtMobile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobile2ActionPerformed(evt);
            }
        });
        txtMobile2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobile2KeyTyped(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lbl_accountType6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_accountType6.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType6.setText("E-mail  @");

        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });

        Fax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fax.setForeground(new java.awt.Color(102, 102, 102));
        Fax.setText("Fax");

        txtContactperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactpersonActionPerformed(evt);
            }
        });

        lbl_description1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_description1.setForeground(new java.awt.Color(102, 102, 102));
        lbl_description1.setText("Customer name");

        txtCreditLimit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCreditLimit.setText("0.00");
        txtCreditLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditLimitActionPerformed(evt);
            }
        });
        txtCreditLimit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreditLimitKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_accountType6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_accountType5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_accountType4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_accountType3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_accountType2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_description1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtAddressline1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtAddressline2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtTele1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(txtTele2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtMobile1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(txtMobile2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Fax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_accountType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContactperson, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_description1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_description, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_accountType2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddressline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_accountType3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddressline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_accountType4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTele1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTele2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_accountType5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMobile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMobile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_accountType6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_accountType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        saveDetail();
        if (atBillingTime) {
            this.dispose();
        }

    }//GEN-LAST:event_btnNewActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
        txtCreditLimit.requestFocus();
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCreditLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditLimitActionPerformed
        // TODO add your handling code here:
        txtAddressline1.requestFocus();
    }//GEN-LAST:event_txtCreditLimitActionPerformed

    private void txtAddressline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressline1ActionPerformed
        // TODO add your handling code here:
        txtAddressline2.requestFocus();
    }//GEN-LAST:event_txtAddressline1ActionPerformed

    private void txtAddressline2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressline2ActionPerformed
        // TODO add your handling code here:
        txtTele1.requestFocus();
    }//GEN-LAST:event_txtAddressline2ActionPerformed

    private void txtTele1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTele1ActionPerformed
        // TODO add your handling code here:
        txtTele2.requestFocus();
    }//GEN-LAST:event_txtTele1ActionPerformed

    private void txtTele2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTele2ActionPerformed
        // TODO add your handling code here:
        txtMobile1.requestFocus();
    }//GEN-LAST:event_txtTele2ActionPerformed

    private void txtMobile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobile1ActionPerformed
        // TODO add your handling code here:
        txtMobile2.requestFocus();
    }//GEN-LAST:event_txtMobile1ActionPerformed

    private void txtMobile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobile2ActionPerformed
        // TODO add your handling code here:
        txtEmail.requestFocus();
    }//GEN-LAST:event_txtMobile2ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        txtFax.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        // TODO add your handling code here:
        txtContactperson.requestFocus();
    }//GEN-LAST:event_txtFaxActionPerformed

    private void txtContactpersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactpersonActionPerformed
        // TODO add your handling code here:
        btnNew.requestFocus();
    }//GEN-LAST:event_txtContactpersonActionPerformed

    private void txtCreditLimitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditLimitKeyTyped
        // TODO add your handling code here:
        Validator.DigitsValitor(evt);
    }//GEN-LAST:event_txtCreditLimitKeyTyped

    private void txtTele1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTele1KeyTyped
        // TODO add your handling code here:
        Validator.TelephoneNoValidate(evt, txtTele1.getText());
    }//GEN-LAST:event_txtTele1KeyTyped

    private void txtTele2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTele2KeyTyped
        // TODO add your handling code here:
        Validator.TelephoneNoValidate(evt, txtTele2.getText());
    }//GEN-LAST:event_txtTele2KeyTyped

    private void txtMobile1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobile1KeyTyped
        // TODO add your handling code here:
        Validator.TelephoneNoValidate(evt, txtMobile1.getText());
    }//GEN-LAST:event_txtMobile1KeyTyped

    private void txtMobile2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobile2KeyTyped
        // TODO add your handling code here:
         Validator.TelephoneNoValidate(evt, txtMobile2.getText());
    }//GEN-LAST:event_txtMobile2KeyTyped

    /**
     * @param args the command line arguments
     */
    private void saveDetail() {
        String Code, Name, CreditLimit, Address1, Address2, Telephone1,
                Telephone2, Mobile1, Mobile2, Email, FaxNum, ContactPerson;

        Name = CheckingSingleQuote.checkSingleQuote(txtCustomerName.getText());
        CreditLimit = txtCreditLimit.getText();
        Address1 = CheckingSingleQuote.checkSingleQuote(txtAddressline1.getText());
        Address2 = CheckingSingleQuote.checkSingleQuote(txtAddressline2.getText());
        Telephone1 = CheckingSingleQuote.checkSingleQuote(txtTele1.getText());
        Telephone2 = CheckingSingleQuote.checkSingleQuote(txtTele2.getText());
        Mobile1 = txtMobile1.getText();
        Mobile2 = txtMobile2.getText();
        Email = CheckingSingleQuote.checkSingleQuote(txtEmail.getText());
        FaxNum = CheckingSingleQuote.checkSingleQuote(txtFax.getText());
        ContactPerson = CheckingSingleQuote.checkSingleQuote(txtContactperson.getText());

        if (!Name.isEmpty() && !CreditLimit.isEmpty()) {
            try {
                Customer customer = new Customer();
                customer.setCus_code(DocCodeGenarate.getCode("CUS"));
                customer.setCus_name(Name);
                customer.setCeditLimit(Double.parseDouble(CreditLimit));
                customer.setActive(1);
                customer.setCus_address1(Address1);
                customer.setCus_address2(Address2);
                customer.setTelNo1(Telephone1);
                customer.setTelNo2(Telephone2);
                customer.setMobileNo1(Mobile1);
                customer.setMobileNo2(Mobile2);
                customer.setEmail(Email);
                customer.setFax(FaxNum);
                customer.setContactPerson(ContactPerson);
                int insertCustomer = CustomerController.insertCustomer(customer);
                if (insertCustomer == 1) {
                    JOptionPane.showMessageDialog(this, "Customer detail successfully saved..");
                    resetAll();

                } else {
                    JOptionPane.showMessageDialog(this, "Customer detail not saved..");
                }
            } catch (SQLException ex) {
                Logger.getLogger(FormNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FormNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill required details..");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fax;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_accountType;
    private javax.swing.JLabel lbl_accountType2;
    private javax.swing.JLabel lbl_accountType3;
    private javax.swing.JLabel lbl_accountType4;
    private javax.swing.JLabel lbl_accountType5;
    private javax.swing.JLabel lbl_accountType6;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_description1;
    private javax.swing.JTextField txtAddressline1;
    private javax.swing.JTextField txtAddressline2;
    private javax.swing.JTextField txtContactperson;
    private javax.swing.JFormattedTextField txtCreditLimit;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtMobile1;
    private javax.swing.JTextField txtMobile2;
    private javax.swing.JTextField txtTele1;
    private javax.swing.JTextField txtTele2;
    // End of variables declaration//GEN-END:variables

    private void resetAll() {
        txtCustomerName.setText("");
        txtCreditLimit.setText("0.00");
        txtAddressline1.setText("");
        txtAddressline2.setText("");
        txtTele1.setText("");
        txtTele2.setText("");
        txtMobile1.setText("");
        txtMobile2.setText("");
        txtEmail.setText("");
        txtFax.setText("");
        txtContactperson.setText("");
        txtCustomerName.requestFocus();
    }
}
