/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import backendcontrollers.OtherPaymentController;
import backendcontrollers.OtherPaymentTypeController;
import functions.CheckingSingleQuote;
import functions.Information;
import functions.Validator;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.OtherPaymentType;
import model.OtherPayments;

/**
 *
 * @author Sameera
 */
public class InternalFrameotherPayment extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameotherPayment
     */
    private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableModel tableModel;

    int pay_id = -1;

    public InternalFrameotherPayment() {
        initComponents();
        calDate.setDateFormat(dateFormat);
        tableModel = (DefaultTableModel) tblpayments.getModel();

        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();

        cellRenderer.setHorizontalAlignment(JLabel.RIGHT);

        tblpayments.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        getAllType();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_newdesc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_newremarks = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCancel1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSave1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmb_paymentType1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txt_desc1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_amount1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_remarks1 = new javax.swing.JTextField();
        btnRefresh1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        calDate = new org.freixas.jcalendar.JCalendarCombo();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpayments = new javax.swing.JTable();
        btnCancel2 = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        mainTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTabMouseClicked(evt);
            }
        });
        mainTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 51, 153));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create New");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 51, 153));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Description :");

        txt_newdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newdescActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Remarks :");

        txt_newremarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newremarksActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(0, 51, 153));
        btnRefresh.setText("New");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_newdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_newremarks, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_newdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_newremarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        mainTab.addTab("Create Payment Type", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCancel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel1.setForeground(new java.awt.Color(0, 51, 153));
        btnCancel1.setText("CANCEL");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(153, 153, 255));
        jLabel6.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Payment detail");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);

        btnSave1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(0, 51, 153));
        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Payment Type  :");

        cmb_paymentType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_paymentType1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_paymentType1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmb_paymentType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_paymentType1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Description :");

        txt_desc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Amount :");

        txt_amount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amount1ActionPerformed(evt);
            }
        });
        txt_amount1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_amount1KeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Remarks :");

        txt_remarks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remarks1ActionPerformed(evt);
            }
        });

        btnRefresh1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefresh1.setForeground(new java.awt.Color(0, 51, 153));
        btnRefresh1.setText("New");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Date           :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_paymentType1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_remarks1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_paymentType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_desc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_amount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_remarks1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainTab.addTab("Enter Payments", jPanel2);

        tblpayments.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblpayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Payment ID", "Date", "Description", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpayments.setRowHeight(18);
        tblpayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpaymentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpayments);
        if (tblpayments.getColumnModel().getColumnCount() > 0) {
            tblpayments.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblpayments.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblpayments.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblpayments.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        btnCancel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel2.setForeground(new java.awt.Color(0, 51, 153));
        btnCancel2.setText("CANCEL");
        btnCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel2ActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 51, 153));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 51, 153));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainTab.addTab("Edit/delete Transactions", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        FormMain.otherPayments.dispose();
        if (FormMain.otherPayments != null) {
            FormMain.otherPayments = null;
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if (!txt_newdesc.getText().isEmpty()) {
            saveNew();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter payment description");
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void txt_newdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newdescActionPerformed
        // TODO add your handling code here:
        txt_newremarks.requestFocus();

    }//GEN-LAST:event_txt_newdescActionPerformed

    private void txt_newremarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newremarksActionPerformed
        // TODO add your handling code here:
        btnSave.requestFocus();
    }//GEN-LAST:event_txt_newremarksActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        getAllType();
        clearInsertAll();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        // TODO add your handling code here:
        FormMain.otherPayments.dispose();
        if (FormMain.otherPayments != null) {
            FormMain.otherPayments = null;
        }
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        if (cmb_paymentType1.getSelectedIndex() != 0) {
            if (!txt_desc1.getText().isEmpty()) {
                if (!txt_amount1.getText().isEmpty()) {
                    if (Double.parseDouble(txt_amount1.getText()) > 0) {
                        saveData();
                    } else {
                        JOptionPane.showMessageDialog(this, "Amount should be greater than 0");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter amount");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please enter payment description");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a payment type");
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void cmb_paymentType1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_paymentType1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cmb_paymentType1.getSelectedIndex() != 0) {
            txt_desc1.setText(cmb_paymentType1.getSelectedItem().toString());
            txt_desc1.requestFocus();
        }
    }//GEN-LAST:event_cmb_paymentType1PopupMenuWillBecomeInvisible

    private void cmb_paymentType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_paymentType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_paymentType1ActionPerformed

    private void txt_desc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc1ActionPerformed
        // TODO add your handling code here:
        txt_amount1.requestFocus();
    }//GEN-LAST:event_txt_desc1ActionPerformed

    private void txt_amount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amount1ActionPerformed
        // TODO add your handling code here:
        txt_remarks1.requestFocus();
    }//GEN-LAST:event_txt_amount1ActionPerformed

    private void txt_amount1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amount1KeyTyped
        // TODO add your handling code here:
        Validator.DigitsValitor(evt);
    }//GEN-LAST:event_txt_amount1KeyTyped

    private void txt_remarks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remarks1ActionPerformed
        // TODO add your handling code here:
        btnSave1.requestFocus();
    }//GEN-LAST:event_txt_remarks1ActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        clearInsertAll();
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void mainTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabStateChanged
        // TODO add your handling code here:
        int selectedIndex = mainTab.getSelectedIndex();
        if (selectedIndex != 1) {
            pay_id = -1;

        }
        if (selectedIndex == 2) {
            viewAll();
        }

    }//GEN-LAST:event_mainTabStateChanged

    private void btnCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel2ActionPerformed
        // TODO add your handling code here:
        FormMain.otherPayments.dispose();
        if (FormMain.otherPayments != null) {
            FormMain.otherPayments = null;
        }
    }//GEN-LAST:event_btnCancel2ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblpayments.getSelectedRow();
        if (tblpayments.isRowSelected(selectedRow)) {
            int confirm = JOptionPane.showConfirmDialog(this, "Do you want to edit this transaction ?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                OtherPayments payment = new OtherPayments();
                int id = Integer.parseInt(tblpayments.getValueAt(selectedRow, 0).toString());
                payment.setId(id);
                OtherPayments tranactionDetail = OtherPaymentController.gettranactionDetail(payment);
                if (tranactionDetail != null) {
                    try {
                        cmb_paymentType1.setSelectedItem(tranactionDetail.getType());
                        calDate.setDate(dateFormat.parse(tranactionDetail.getDate()));
                        txt_desc1.setText(tranactionDetail.getDescription());
                        txt_amount1.setText(tranactionDetail.getAmount() + "");
                        txt_remarks1.setText(tranactionDetail.getRemark());
                        pay_id = id;
                        mainTab.setSelectedIndex(1);

                    } catch (ParseException ex) {
                        Logger.getLogger(InternalFrameotherPayment.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "cannot find details to edit.");

                }
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblpayments.getSelectedRow();
        if (tblpayments.isRowSelected(selectedRow)) {
            int confirm = JOptionPane.showConfirmDialog(this, "Do you want to delete this transaction ?", "Confirm", JOptionPane.YES_NO_OPTION);

            if (confirm == 0) {
                OtherPayments payments = new OtherPayments();
                payments.setId(Integer.parseInt(tblpayments.getValueAt(selectedRow, 0).toString()));
                int deleteTransaction = OtherPaymentController.deleteTransaction(payments);
                if (deleteTransaction == 1) {
                    JOptionPane.showMessageDialog(null, "Transaction deleted..");
                    viewAll();
                } else {
                    JOptionPane.showMessageDialog(null, "Transaction not deleted..");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete", "No row selected", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void mainTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTabMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mainTabMouseClicked

    private void tblpaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpaymentsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblpaymentsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnCancel2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private org.freixas.jcalendar.JCalendarCombo calDate;
    private javax.swing.JComboBox cmb_paymentType1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JTable tblpayments;
    private javax.swing.JTextField txt_amount1;
    private javax.swing.JTextField txt_desc1;
    private javax.swing.JTextField txt_newdesc;
    private javax.swing.JTextField txt_newremarks;
    private javax.swing.JTextField txt_remarks1;
    // End of variables declaration//GEN-END:variables

    private void saveData() {
        try {
            String type = cmb_paymentType1.getSelectedItem().toString();
            String desc = CheckingSingleQuote.checkSingleQuote(txt_desc1.getText());
            double amount = Double.parseDouble(Validator.BuildTwoDecimals(Double.parseDouble(txt_amount1.getText())));
            String date = dateFormat.format(calDate.getDate());
            String user = Information.intilzeInformation().getUserID();
            String remark = txt_remarks1.getText();

            SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
            Date date1 = new Date();
            String time = format.format(date1);
            OtherPayments payments = new OtherPayments();
            payments.setType(type);
            payments.setDescription(desc);
            payments.setDate(date);
            payments.setTime(time);
            payments.setAmount(amount);
            payments.setUser(user);
            payments.setRemark(remark);
            int insertOrderPayment = 0;
            if (pay_id == -1) {
                insertOrderPayment = OtherPaymentController.insertOrderPayment(payments);
                if (insertOrderPayment == 1) {
                    JOptionPane.showMessageDialog(this, "Details successfully Saved..");
                    clearInsertAll();
                } else {
                    JOptionPane.showMessageDialog(this, "Details Saved not successfully ..");
                }
            } else {
                payments.setId(pay_id);
                int updated = OtherPaymentController.updateDetails(payments);
                if (updated == 1) {
                    JOptionPane.showMessageDialog(this, "Details successfully updated..");
                    clearInsertAll();
                    pay_id = -1;
                } else {
                    JOptionPane.showMessageDialog(this, "Details update not successfully ..");
                }

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InternalFrameotherPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(InternalFrameotherPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearInsertAll() {
        cmb_paymentType1.setSelectedIndex(0);
        txt_amount1.setText("");
        txt_desc1.setText("");
        txt_remarks1.setText("");
        cmb_paymentType1.requestFocus();
    }

    private void getAllType() {
        try {
            // TODO add your handling code here:
            int index = 1;
            String select = "--Select-- ";
            cmb_paymentType1.removeAllItems();
            cmb_paymentType1.insertItemAt(select, 0);
            ArrayList<OtherPaymentType> types = OtherPaymentTypeController.getAll();
            for (OtherPaymentType otherPaymentType : types) {
                cmb_paymentType1.insertItemAt(otherPaymentType.getDescription(), index);
                index++;
            }
            cmb_paymentType1.setSelectedIndex(0);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InternalFrameotherPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(InternalFrameotherPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveNew() {
        try {
            OtherPaymentType type = new OtherPaymentType();
            type.setDescription(txt_newdesc.getText());
            type.setRemark(txt_newremarks.getText());
            int insertNew = OtherPaymentTypeController.insertNew(type);
            if (insertNew == 1) {
                JOptionPane.showMessageDialog(this, "Details successfully Saved..");
                clearNewAll();
            } else {
                JOptionPane.showMessageDialog(this, "Details not Saved..");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InternalFrameotherPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(InternalFrameotherPayment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void clearNewAll() {
        txt_newdesc.setText("");
        txt_newremarks.setText("");
        txt_newdesc.requestFocus();
    }

    private void viewAll() {
        if (mainTab.getSelectedIndex() == 2) {
            try {
                ArrayList<OtherPayments> allTransactions = OtherPaymentTypeController.getAllTransactions();
                tableModel.setRowCount(0);
                for (OtherPayments otherPayments : allTransactions) {
                    tableModel.addRow(new Object[]{otherPayments.getId(), otherPayments.getDate(), otherPayments.getDescription(), otherPayments.getAmount()});
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(InternalFrameotherPayment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(InternalFrameotherPayment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
